# Generated by Django 3.0.3 on 2020-03-11 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200311_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='question',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Интерес'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anwer', models.CharField(default='', max_length=255, verbose_name='Ответ')),
                ('question', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Question')),
                ('tags', models.ManyToManyField(to='users.Tag')),
            ],
        ),
    ]
