# Generated by Django 3.0.3 on 2020-03-31 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_mentoruser_studentuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='userform',
            options={'verbose_name': 'Ответ студента', 'verbose_name_plural': 'Ответы студентов'},
        ),
        migrations.AddField(
            model_name='user',
            name='referral_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='07e9e84e-122e-4158-9cb5-615221be3f66', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='referred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
