# Generated by Django 3.0.3 on 2020-03-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200331_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='3e9a9e6c-05bf-42a5-88dd-b74b5608f9a4', max_length=255, unique=True),
        ),
    ]
