# Generated by Django 3.0.3 on 2020-03-31 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200331_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
