# Generated by Django 3.0.3 on 2020-03-13 14:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_user_done_form'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название урока')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название модуля')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание модуля')),
                ('lessons', models.ManyToManyField(blank=True, default='', null=True, to='course.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя спикера')),
                ('description', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('is_lead', models.BooleanField(default=False, verbose_name='Лид спикер')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='lessons_video/')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Proffesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проффесии')),
                ('tags', models.ManyToManyField(related_name='tags', to='users.Tag', verbose_name='Навыки')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название пакета')),
                ('description', ckeditor.fields.RichTextField()),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('duration', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='длительность')),
                ('feature', models.CharField(max_length=500, verbose_name='Фича')),
                ('is_sale', models.BooleanField(default=False, verbose_name='По акции')),
                ('new_price', models.IntegerField(blank=True, null=True, verbose_name='Новая цена ')),
                ('modules', models.ManyToManyField(related_name='modules', to='course.Module')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='lessons_files/')),
                ('lesson', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('description', ckeditor.fields.RichTextField()),
                ('duration', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='длительность')),
                ('packages', models.ManyToManyField(to='course.Package', verbose_name='Пакеты')),
                ('proffesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Proffesion', verbose_name='Проффесия')),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Speaker', verbose_name='Спикер')),
                ('tags', models.ManyToManyField(to='users.Tag')),
            ],
        ),
    ]
