# Generated by Django 3.0.3 on 2020-03-13 15:58

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='packages',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='course.Package', verbose_name='Пакеты'),
        ),
    ]
