# Generated by Django 3.0.3 on 2020-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200313_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='packages',
            field=models.ManyToManyField(to='course.Package', verbose_name='Пакеты'),
        ),
    ]
