# Generated by Django 3.0.3 on 2020-03-16 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200313_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Пакет', 'verbose_name_plural': 'Пакеты'},
        ),
        migrations.AlterModelOptions(
            name='proffesion',
            options={'verbose_name': 'Проффесия', 'verbose_name_plural': 'Проффесии'},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'verbose_name': 'Спикер', 'verbose_name_plural': 'Спикеры'},
        ),
        migrations.AlterField(
            model_name='lessonfile',
            name='lesson',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_file', to='course.Lesson'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_video', to='course.Lesson'),
        ),
    ]
