# Generated by Django 3.0.3 on 2020-03-17 09:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200316_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='home_task/')),
                ('text', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('lesson', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Lesson')),
            ],
        ),
    ]
