# Generated by Django 3.0.3 on 2020-03-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_hometask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometask',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='task',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.HomeTask'),
        ),
    ]
