# Generated by Django 3.0.3 on 2020-03-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200317_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='task',
        ),
        migrations.AddField(
            model_name='hometask',
            name='lesson',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Lesson'),
        ),
    ]
