# Generated by Django 3.0.3 on 2020-03-17 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0007_auto_20200317_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometask',
            name='file_answer',
            field=models.FileField(blank=True, null=True, upload_to='home_task/'),
        ),
        migrations.AddField(
            model_name='hometask',
            name='status',
            field=models.CharField(choices=[('done', 'Сдано'), ('not_done', 'Не сдано'), ('wait', 'На проверке')], default='not_done', max_length=20),
        ),
        migrations.AddField(
            model_name='hometask',
            name='text_answer',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='hometask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
