# Generated by Django 3.0.3 on 2020-03-18 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20200318_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometask',
            name='file_answer',
        ),
        migrations.RemoveField(
            model_name='hometask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='hometask',
            name='text_answer',
        ),
        migrations.RemoveField(
            model_name='hometask',
            name='user',
        ),
        migrations.AlterField(
            model_name='hometask',
            name='lesson',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Lesson'),
        ),
    ]
