# Generated by Django 3.0.3 on 2020-03-19 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20200318_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='origin_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Package'),
        ),
    ]
