# Generated by Django 3.0.3 on 2020-03-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_package_origin_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
