# Generated by Django 3.0.3 on 2020-03-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='modules',
            field=models.ManyToManyField(null=True, related_name='modules', to='course.Module'),
        ),
    ]
