# Generated by Django 3.0.3 on 2020-03-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20200319_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название видео'),
        ),
    ]
