# Generated by Django 3.0.3 on 2020-03-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_auto_20200320_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='modules',
            field=models.ManyToManyField(blank=True, null=True, related_name='modules', to='course.Module'),
        ),
    ]
