# Generated by Django 3.0.3 on 2020-03-20 15:19

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField

class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20200320_1519'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='package',
            name='modules',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='modules', to='course.Module'),
        ),
    ]
