# Generated by Django 3.0.3 on 2020-03-24 10:54

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_auto_20200320_1519'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='module',
            name='lessons',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, default='', help_text=None, null=True, to='course.Lesson'),
        ),
    ]
