# Generated by Django 3.0.3 on 2020-03-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_auto_20200324_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='full_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='full_image_course/'),
        ),
        migrations.AddField(
            model_name='course',
            name='small_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='small_image_course/'),
        ),
    ]
