# Generated by Django 3.0.3 on 2020-03-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_auto_20200324_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='video_1080',
            field=models.FileField(blank=True, null=True, upload_to='lessons_video_1080/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_360',
            field=models.FileField(blank=True, null=True, upload_to='lessons_video_360/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_720',
            field=models.FileField(blank=True, null=True, upload_to='lessons_video_720/'),
        ),
    ]
