# Generated by Django 3.0.3 on 2020-03-26 09:09

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0023_auto_20200324_1643'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='course',
            name='packages',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='course.Package', verbose_name='Пакеты'),
        ),
    ]
