# Generated by Django 3.0.3 on 2020-03-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_auto_20200326_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometask',
            name='lesson',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='course.Lesson'),
        ),
    ]
