# Generated by Django 3.0.3 on 2020-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_auto_20200326_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTaskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='home_task/')),
            ],
        ),
        migrations.RemoveField(
            model_name='hometask',
            name='file',
        ),
        migrations.AddField(
            model_name='hometask',
            name='file',
            field=models.ManyToManyField(to='course.HomeTaskFile'),
        ),
    ]
