# Generated by Django 3.0.3 on 2020-03-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_auto_20200326_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometask',
            name='file',
            field=models.ManyToManyField(related_name='files', to='course.HomeTaskFile'),
        ),
    ]
