# Generated by Django 3.0.3 on 2020-04-02 10:06

import ckeditor_uploader.fields
from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_speaker_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок статьи')),
                ('desc', models.TextField(max_length=500, verbose_name='Краткое описание статьи')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент')),
                ('status', models.BooleanField(default=True, verbose_name='В публикацию')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='articles/')),
                ('count_views', models.IntegerField(default=0)),
                ('articles', sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='_article_articles_+', to='course.Article', verbose_name='Читайте также')),
            ],
        ),
    ]
