# Generated by Django 3.0.3 on 2020-04-02 10:10

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articles',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='_article_articles_+', to='course.Article', verbose_name='Читайте также'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
