# Generated by Django 3.0.3 on 2020-04-08 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_auto_20200402_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Speaker'),
        ),
        migrations.AddField(
            model_name='article',
            name='lead',
            field=models.TextField(default='', max_length=500, verbose_name='Ключевые моменты статьи (Лид)'),
        ),
    ]
