# Generated by Django 3.0.3 on 2020-03-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0010_auto_20200317_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTaskStudent',
            fields=[
            ],
            options={
                'verbose_name': 'Домашка студентa',
                'verbose_name_plural': 'Домашки студентов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('course.hometask',),
        ),
    ]
