# Generated by Django 3.0.3 on 2020-03-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_package_origin_package'),
        ('student', '0005_userhometask_has_home_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPackage',
            fields=[
            ],
            options={
                'verbose_name': 'пакет студента',
                'verbose_name_plural': 'пакеты студентов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('course.package',),
        ),
    ]
