# Generated by Django 3.0.3 on 2020-03-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200319_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhometask',
            name='answer',
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_answer', models.FileField(blank=True, null=True, upload_to='file_answer/')),
                ('text_answer', models.TextField(max_length=5000, verbose_name='Текст ответа')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.UserHomeTask')),
            ],
        ),
    ]
