# Generated by Django 3.0.3 on 2020-03-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20200319_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhometask',
            name='status',
            field=models.CharField(choices=[('done', 'Сдано'), ('not_done', 'Не сдано'), ('wait', 'На проверке')], default='not_done', max_length=20),
        ),
    ]
